# Generated by Django 4.1 on 2023-11-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('PLANETA', 'planeta'), ('ESTRELA', 'estrela'), ('GALÁXIA', 'galaxia'), ('NEBULOSA', 'nebulosa')], default='', max_length=100),
        ),
    ]
