# Generated by Django 4.1 on 2023-11-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('PLANETA', 'planeta'), ('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela'), ('GALÁXIA', 'galaxia')], default='', max_length=100),
        ),
    ]
