# Generated by Django 4.1 on 2023-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('ESTRELA', 'estrela'), ('NEBULOSA', 'nebulosa'), ('GALÁXIA', 'galaxia'), ('PLANETA', 'planeta')], default='', max_length=100),
        ),
    ]
